Added the facter command to check os details
6WIND/zrpcd pull request #19
Opened 2017-07-25 07:08 UTC by maheshloni

As per CSIT community , Need to proper command to fetch the OS details

2017-07-25 15:33 UTC, pguibert6WIND requested changes
except for the copyright.
I agree with the rest of the commit

2017-07-25 15:33 UTC, pguibert6WIND commented on pkgsrc/dev_compile_script.sh
>  #
a copyright is never changed
if you want to add Ericsson, please append, but not replace not remove.
thanks

2017-07-25 15:58 UTC, maheshloni commented
Philippe, 
I have updated your review comments

2017-07-26 08:39 UTC, maheshloni reviewed
updated the review comments

2017-07-26 08:41 UTC, maheshloni commented
Please merge to master as well as 20170418 and 20170330 release tags

2017-07-26 09:00 UTC, pguibert6WIND approved these changes

2017-07-26 09:02 UTC, pguibert6WIND approved these changes

2017-07-26 09:02 UTC, merged